### ISSUE TITLE
签名算法错误

### ISSUE THREAD

**Issue by zorrosopc** [Aries-orz/nano-sm2#2]
参考《国密算法SM2.pdf》里的示例：
椭圆曲线方程为：y2 = x3 + ax + b
示例1：Fp-256
素数p：
8542D69E 4C044F18 E8B92435 BF6FF7DE 45728391 5C45517D 722EDB8B 08F1DFC3
系数a：
787968B4 FA32C3FD 2417842E 73BBFEFF 2F3C848B 6831D7E0 EC65228B 3937E498
系数b：
63E4C6D3 B23B0C84 9CF84241 484BFE48 F61D59A5 B16BA06E 6E12D1DA 27C5249A
基点G=(xG,yG)，其阶记为n。
坐标xG：
421DEBD6 1B62EAB6 746434EB C3CC315E 32220B3B ADD50BDC 4C4E6C14 7FEDD43D
坐标yG：
0680512B CBB42C07 D47349D2 153B70C4 E5D7FDFC BFA36EA1 A85841B9 E46E09A2
阶n：
8542D69E 4C044F18 E8B92435 BF6FF7DD 29772063 0485628D 5AE74EE7 C32E79B7
待签名的消息M：message digest
私钥dA：
128B2FA8 BD433C6C 068C8D80 3DFF7979 2A519A55 171B1B65 0C23661D 15897263
公钥PA=(xA,yA)：
坐标xA：
0AE4C779 8AA0F119 471BEE11 825BE462 02BB79E2 A5844495 E97C04FF 4DF2548A
坐标yA：
7C0240F8 8F1CD4E1 6352A73C 17B7F16F 07353E53 A176D684 A9FE0C6B B798E857
杂凑值ZA=H256(ENTLA ∥ IDA ∥ a ∥ b ∥ xG ∥ yG ∥ xA ∥ yA)。
ZA：
F4A38489 E32B45B6 F876E3AC 2168CA39 2362DC8F 23459C1D 1146FC3D BFB7BC9A
签名各步骤中的有关值：
M=ZA ∥ M：
F4A38489 E32B45B6 F876E3AC 2168CA39 2362DC8F 23459C1D 1146FC3D BFB7BC9A
6D657373 61676520 64696765 7374
7
密码杂凑函数值e=H256(M)：
B524F552 CD82B8B0 28476E00 5C377FB1 9A87E6FC 682D48BB 5D42E3D9 B9EFFE76
产生随机数k：
6CB28D99 385C175C 94F94E93 4817663F C176D925 DD72B727 260DBAAE 1FB2F96F
计算椭圆曲线点(x1,y1)=[k]G：
坐标x1：
110FCDA5 7615705D 5E7B9324 AC4B856D 23E6D918 8B2AE477 59514657 CE25D112
坐标y1：
1C65D68A 4A08601D F24B431E 0CAB4EBE 084772B3 817E8581 1A8510B2 DF7ECA1A
计算r=(e+x1) modn：
40F1EC59 F793D9F4 9E09DCEF 49130D41 94F79FB1 EED2CAA5 5BACDB49 C4E755D1
(1 + dA)
−1：
79BFCF30 52C80DA7 B939E0C6 914A18CB B2D96D85 55256E83 122743A7 D4F5F956
计算s = ((1 + dA)−1 · (k − r · dA)) modn：
6FC6DAC3 2C5D5CF1 0C77DFB2 0F7C2EB6 67A45787 2FB09EC5 6327A67E C7DEEBE7
消息M的签名为(r,s)：
值r：
40F1EC59 F793D9F4 9E09DCEF 49130D41 94F79FB1 EED2CAA5 5BACDB49 C4E755D1
值s：
6FC6DAC3 2C5D5CF1 0C77DFB2 0F7C2EB6 67A45787 2FB09EC5 6327A67E C7DEEBE7

**EccPoint_mult(&p, &curve_G, k, NULL);**
**k*G的结果不对啊，咋回事？**

**Comment by Aries-orz** [comment]
本算法实现只对说明里最下面附上的256位SM2官方推荐参数有效，其他的SM2参数暂时不能用（因为计算过程针对这组参数的数学性质进行了优化），请知悉。之后有时间的话会继续维护，尽可能支持所有参数
