### ISSUE TITLE
SM2推荐参数的疑问

### ISSUE THREAD

**Issue by xuebo2215** [Aries-orz/nano-sm2#3]
另附本代码使用的SM2官方推荐参数（256位）：
椭圆曲线方程：y^2 = x^3 + ax + b
曲线参数：
p=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFF
a=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFC
b=28E9FA9E 9D9F5E34 4D5A9E4B CF6509A7 F39789F5 15AB8F92 DDBCBD41 4D940E93
n=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF 7203DF6B 21C6052B 53BBF409 39D54123
Gx=32C4AE2C 1F198119 5F990446 6A39C994 8FE30BBF F2660BE1 715A4589 334C74C7
Gy=BC3736A2 F4F6779C 59BDCEE3 6B692153 D0A9877C C62A4740 02DF32E5 2139F0A0

我看代码里 a那个参数并没有用到，是不需要么？

**Comment by Aries-orz** [comment]
a用到了。
只不过因为 a mod p = (-3) mod p，所以利用这一性质，使用时直接把a定义成了-3。

**Comment by xuebo2215** [comment]
好的，谢谢
